### PR TITLE
CentOS support and cleanups

### PR DESCRIPTION
**Pull request by haf**
This pull request merges fixes gained from trying to get this to run in vagrant, with some code improvemens (mixsvc), with @metcalfc CentOS branch in issue #1.

This pull request is not complete, but I need sleep, too. I welcome any feedback you may have.

### CODE REVIEW

**Comment by garethr** [comment]
I just made quite a large refactor of this module at the exact same time, and I disagree with a few bits here (explicit package references for instance) but I will get Centos support in, especially as you've done all the hard work. Thanks, and sorry I can't just merge this straight away.

**Comment by haf** [comment]
Hi,

Could you please expand on what you mean by 'explicit package references'? Do you mean to depend on epel despite not needing it for both debian and rhel? Are there any other things you disagree with and why in that case? (wanting to learn)

I'm nearly there with CentOS services now.

Henrik

**Comment by haf** [comment]
Btw, I have also introduced a user per service, using setuid in the upstart configuration files.

**Comment by garethr** [comment]
actually, I'd missed the ensure_packages trick. I'm travelling for the next few days but once I've got the bandwidth to get a centos box to test things out I'll go through in more details. Thanks again

**Comment by haf** [comment]
Alright, closing.

**Pull request closed without merging**
