### PR TITLE
Add support for CentOS

### PR DESCRIPTION
**Pull request by metcalfc**
What it says on the tin. Large change. The failures in travis seem to be a problem with my use of rspec-puppet and functions. Not sure how to fix those (but they should be fixed, it works in the wild).

### CODE REVIEW

**Comment by metcalfc** [comment]
@garethr Have you had a chance to take a look at this? Its a big revision and I'm open to moving things around.

**Comment by garethr** [comment]
Sorry, I've not had a chance to take a look yet. I'm crazily busy at work and will be until probably the end of October. I'll definitely take a look then. I also noticed that Travis things the tests have problems: https://travis-ci.org/#!/garethr/garethr-riemann/pull_requests Not sure if this is directly related to these changes or not?

**Comment by metcalfc** [comment]
The tests aren't happy at the moment. I've added a function which
rspec_puppet doesn't like. I think it should work there is just some rspec
puppet magic I'm not doing.

It actually won't matter much longer, I've got the function upstreamed to
stdlib and I'm hoping that pull request closes today. I'll rebase that
change out once thats done.

**Comment by stahnma** [comment]
Any progress on this? I wanted to play with Rieman on CentOS today :)

**Comment by metcalfc** [comment]
Yikes. I have dropped the ball here. I'll rebase and get this updated.

**Comment by haf** [comment]
Any news?

**Comment by metcalfc** [comment]
i'm hoping on this during the monitorama hackathon tomorrow

**Comment by garethr** [comment]
I'm at monitorama too, happy to help and get it merged.

**Comment by haf** [comment]
How has it gone? I'm gonna start hacking on this now.

**Comment by garethr** [comment]
Pull request #4, which I've just merged, adds support for Centos. Thanks for the work on both the branches for this, and let me know if you get a chance to try the module out. It's available on the forge as well as 0.3.1 and the supporting riemann-vagrant project has been updated with a Centos demo. Cheers all

**Pull request closed without merging**
